name: Python Ci

on:
    push:
        branches: [main]

jobs:
    my-python-app:
        runs-on: ubuntu-latest

        steps:
         -  name: Git Checkout
            uses: actions/checkout@v4

         -  name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'

         -  name: Run App
            run: python app.py